services:
  mariadb:
    image: mariadb:lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  bot:
    image: bigpoint/discord-bot
    build:
      context: .
      dockerfile: ./packages/bot/Dockerfile.bot
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes: 
      - ./packages/ui/src:/var/www/html
      - ./packages/ui/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php-with-ext
    build: 
      dockerfile: ./packages/ui/Dockerfile.ui
      context: .
    volumes:
      - ./packages/ui/src:/var/www/html

volumes:
  data: