services:
  mariadb:
    image: mariadb:lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  bot:
    image: bigpoint/discord-bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    ports: 
      - "8080:8080"
  ui:
    image: bigpoint/discord-ui-dev
    build:
      context: .
      dockerfile: Dockerfile.ui.dev
    volumes:
      - ./packages/ui/src:/opt/app/packages/ui/src
    env_file: .env
    ports:
      - '4000:4000'

volumes:
  data: