services:
  mariadb:
    image: mariadb:lts
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  bot:
    image: bigpoint/discord-bot
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: .env
    ports: 
      - "8080:8080"
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes: 
      - ./packages/ui/src/web:/var/www/html
      - ./packages/ui/default.conf:/etc/nginx/conf.d/default.conf
  ui:
    image: bigpoint/discord-ui-dev
    build:
      context: .
      dockerfile: Dockerfile.ui.dev
    volumes:
      - .:/opt/app/

volumes:
  data: