*

.yarn/*
!.yarn/cache
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions

!package.json
!yarn.lock
!.yarnrc.yml
!tsconfig.json

!packages/bot/package.json
!packages/bot/tsconfig.json
!packages/bot/src/*
!packages/lib-*/package.json
!packages/lib-*/tsconfig.json
!packages/lib-*/src/*