.dist
sql
.vscode
.github
.gitignore
node_modules
.yarn/*
!.yarn/cache
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions
docker-compose.yaml

packages/*
!packages/ui

yarn-error.log
.git
Dockerfile*
.env.default
.parcel-cache